from project import read
from project import get_dict
from project import check_values

dictitonary = [{'index': 0, 'value': 0, 'row': 0, 'column': 0, 'box': 0, 'potential': False, 'solid': False}, {'index': 1, 'value': 1, 'row': 0, 'column': 1, 'box': 0, 'potential': False, 'solid': True}, {'index': 2, 'value': 0, 'row': 0, 'column': 2, 'box': 0, 'potential': False, 'solid': False}, {'index': 3, 'value': 0, 'row': 0, 'column': 3, 'box': 1, 'potential': False, 'solid': False}, {'index': 4, 'value': 0, 'row': 0, 'column': 4, 'box': 1, 'potential': False, 'solid': False}, {'index': 5, 'value': 0, 'row': 0, 'column': 5, 'box': 1, 'potential': False, 'solid': False}, {'index': 6, 'value': 8, 'row': 0, 'column': 6, 'box': 2, 'potential': False, 'solid': True}, {'index': 7, 'value': 9, 'row': 0, 'column': 7, 'box': 2, 'potential': False, 'solid': True}, {'index': 8, 'value': 0, 'row': 0, 'column': 8, 'box': 2, 'potential': False, 'solid': False}, {'index': 9, 'value': 7, 'row': 1, 'column': 0, 'box': 0, 'potential': False, 'solid': True}, {'index': 10, 'value': 8, 'row': 1, 'column': 1, 'box': 0, 'potential': False, 'solid': True}, {'index': 11, 'value': 0, 'row': 1, 'column': 2, 'box': 0, 'potential': False, 'solid': False}, {'index': 12, 'value': 0, 'row': 1, 'column': 3, 'box': 1, 'potential': False, 'solid': False}, {'index': 13, 'value': 0, 'row': 1, 'column': 4, 'box': 1, 'potential': False, 'solid': False}, {'index': 14, 'value': 1, 'row': 1, 'column': 5, 'box': 1, 'potential': False, 'solid': True}, {'index': 15, 'value': 5, 'row': 1, 'column': 6, 'box': 2, 'potential': False, 'solid': True}, {'index': 16, 'value': 0, 'row': 1, 'column': 7, 'box': 2, 'potential': False, 'solid': False}, {'index': 17, 'value': 0, 'row': 1, 'column': 8, 'box': 2, 'potential': False, 'solid': False}, {'index': 18, 'value': 0, 'row': 2, 'column': 0, 'box': 0, 'potential': False, 'solid': False}, {'index': 19, 'value': 0, 'row': 2, 'column': 1, 'box': 0, 'potential': False, 'solid': False}, {'index': 20, 'value': 6, 'row': 2, 'column': 2, 'box': 0, 'potential': False, 'solid': True}, {'index': 21, 'value': 0, 'row': 2, 'column': 3, 'box': 1, 'potential': False, 'solid': False}, {'index': 22, 'value': 0, 'row': 2, 'column': 4, 'box': 1, 'potential': False, 'solid': False}, {'index': 23, 'value': 5, 'row': 2, 'column': 5, 'box': 1, 'potential': False, 'solid': True}, {'index': 24, 'value': 0, 'row': 2, 'column': 6, 'box': 2, 'potential': False, 'solid': False}, {'index': 25, 'value': 1, 'row': 2, 'column': 7, 
'box': 2, 'potential': False, 'solid': True}, {'index': 26, 'value': 0, 'row': 2, 'column': 8, 'box': 2, 'potential': False, 'solid': False}, {'index': 27, 'value': 3, 'row': 3, 'column': 0, 'box': 3, 'potential': False, 'solid': True}, {'index': 28, 'value': 9, 'row': 3, 'column': 1, 
'box': 3, 'potential': False, 'solid': True}, {'index': 29, 'value': 8, 'row': 3, 'column': 2, 'box': 3, 'potential': False, 'solid': True}, {'index': 30, 'value': 0, 'row': 3, 'column': 3, 'box': 4, 'potential': False, 'solid': False}, {'index': 31, 'value': 6, 'row': 3, 'column': 4, 
'box': 4, 'potential': False, 'solid': True}, {'index': 32, 'value': 2, 'row': 3, 'column': 5, 'box': 4, 'potential': False, 'solid': True}, {'index': 33, 'value': 0, 'row': 3, 'column': 6, 'box': 5, 'potential': False, 'solid': False}, {'index': 34, 'value': 0, 'row': 3, 'column': 7, 
'box': 5, 'potential': False, 'solid': False}, {'index': 35, 'value': 0, 'row': 3, 'column': 8, 'box': 5, 'potential': False, 'solid': False}, 
{'index': 36, 'value': 0, 'row': 4, 'column': 0, 'box': 3, 'potential': False, 'solid': False}, {'index': 37, 'value': 5, 'row': 4, 'column': 1, 'box': 3, 'potential': False, 'solid': True}, {'index': 38, 'value': 4, 'row': 4, 'column': 2, 'box': 3, 'potential': False, 'solid': True}, 
{'index': 39, 'value': 0, 'row': 4, 'column': 3, 'box': 4, 'potential': False, 'solid': False}, {'index': 40, 'value': 0, 'row': 4, 'column': 4, 'box': 4, 'potential': False, 'solid': False}, {'index': 41, 'value': 3, 'row': 4, 'column': 5, 'box': 4, 'potential': False, 'solid': True}, {'index': 42, 'value': 0, 'row': 4, 'column': 6, 'box': 5, 'potential': False, 'solid': False}, {'index': 43, 'value': 2, 'row': 4, 'column': 
7, 'box': 5, 'potential': False, 'solid': True}, {'index': 44, 'value': 8, 'row': 4, 'column': 8, 'box': 5, 'potential': False, 'solid': True}, {'index': 45, 'value': 1, 'row': 5, 'column': 0, 'box': 3, 'potential': False, 'solid': True}, {'index': 46, 'value': 0, 'row': 5, 'column': 1, 'box': 3, 'potential': False, 'solid': False}, {'index': 47, 'value': 0, 'row': 5, 'column': 2, 'box': 3, 'potential': False, 'solid': False}, {'index': 48, 'value': 4, 'row': 5, 'column': 3, 'box': 4, 'potential': False, 'solid': True}, {'index': 49, 'value': 0, 'row': 5, 'column': 
4, 'box': 4, 'potential': False, 'solid': False}, {'index': 50, 'value': 8, 'row': 5, 'column': 5, 'box': 4, 'potential': False, 'solid': True}, {'index': 51, 'value': 9, 'row': 5, 'column': 6, 'box': 5, 'potential': False, 'solid': True}, {'index': 52, 'value': 0, 'row': 5, 'column': 
7, 'box': 5, 'potential': False, 'solid': False}, {'index': 53, 'value': 6, 'row': 5, 'column': 8, 'box': 5, 'potential': False, 'solid': True}, {'index': 54, 'value': 5, 'row': 6, 'column': 0, 'box': 6, 'potential': False, 'solid': True}, {'index': 55, 'value': 0, 'row': 6, 'column': 
1, 'box': 6, 'potential': False, 'solid': False}, {'index': 56, 'value': 0, 'row': 6, 'column': 2, 'box': 6, 'potential': False, 'solid': False}, {'index': 57, 'value': 2, 'row': 6, 'column': 3, 'box': 7, 'potential': False, 'solid': True}, {'index': 58, 'value': 0, 'row': 6, 'column': 4, 'box': 7, 'potential': False, 'solid': False}, {'index': 59, 'value': 6, 'row': 6, 'column': 5, 'box': 7, 'potential': False, 'solid': True}, {'index': 60, 'value': 3, 'row': 6, 'column': 6, 'box': 8, 'potential': False, 'solid': True}, {'index': 61, 'value': 8, 'row': 6, 'column': 7, 'box': 8, 'potential': False, 'solid': True}, {'index': 62, 'value': 9, 'row': 6, 'column': 8, 'box': 8, 'potential': False, 'solid': True}, {'index': 63, 'value': 9, 'row': 7, 'column': 0, 'box': 6, 'potential': False, 'solid': True}, {'index': 64, 'value': 0, 'row': 7, 'column': 
1, 'box': 6, 'potential': False, 'solid': False}, {'index': 65, 'value': 2, 'row': 7, 'column': 2, 'box': 6, 'potential': False, 'solid': True}, {'index': 66, 'value': 0, 'row': 7, 'column': 3, 'box': 7, 'potential': False, 'solid': False}, {'index': 67, 'value': 0, 'row': 7, 'column': 4, 'box': 7, 'potential': False, 'solid': False}, {'index': 68, 'value': 7, 'row': 7, 'column': 5, 'box': 7, 'potential': False, 'solid': True}, {'index': 69, 'value': 4, 'row': 7, 'column': 6, 'box': 8, 'potential': False, 'solid': True}, {'index': 70, 'value': 5, 'row': 7, 'column': 7, 'box': 8, 'potential': False, 'solid': True}, {'index': 71, 'value': 0, 'row': 7, 'column': 8, 'box': 8, 'potential': False, 'solid': False}, {'index': 72, 'value': 8, 'row': 8, 'column': 0, 'box': 6, 'potential': False, 'solid': True}, {'index': 73, 'value': 0, 'row': 8, 'column': 1, 'box': 6, 'potential': False, 'solid': False}, {'index': 74, 'value': 3, 'row': 8, 'column': 2, 'box': 6, 'potential': False, 'solid': True}, {'index': 75, 'value': 5, 'row': 8, 'column': 3, 'box': 7, 'potential': False, 'solid': True}, {'index': 76, 'value': 0, 'row': 8, 'column': 4, 'box': 7, 'potential': False, 'solid': False}, {'index': 77, 'value': 0, 'row': 8, 'column': 5, 'box': 7, 'potential': False, 'solid': False}, {'index': 78, 'value': 0, 'row': 8, 'column': 6, 'box': 8, 'potential': False, 'solid': False}, {'index': 79, 'value': 0, 'row': 8, 'column': 7, 'box': 8, 'potential': False, 'solid': False}, {'index': 80, 'value': 2, 'row': 8, 'column': 8, 'box': 8, 'potential': False, 'solid': True}]

result = [{'index': 0, 'value': 2, 'row': 0, 'column': 0, 'box': 0, 'potential': [4], 'solid': False}, {'index': 1, 'value': 1, 'row': 0, 'column': 1, 'box': 0, 'potential': False, 'solid': True}, {'index': 2, 'value': 5, 'row': 0, 'column': 2, 'box': 0, 'potential': False, 'solid': False}, {'index': 3, 'value': 6, 'row': 0, 'column': 3, 'box': 1, 'potential': [7], 'solid': False}, {'index': 4, 'value': 7, 'row': 0, 'column': 4, 'box': 1, 'potential': False, 'solid': False}, {'index': 5, 'value': 4, 'row': 0, 'column': 5, 'box': 1, 'potential': False, 'solid': False}, {'index': 6, 'value': 8, 'row': 0, 'column': 6, 'box': 2, 'potential': False, 'solid': True}, {'index': 7, 'value': 9, 'row': 0, 'column': 7, 'box': 
2, 'potential': False, 'solid': True}, {'index': 8, 'value': 3, 'row': 0, 'column': 8, 'box': 2, 'potential': False, 'solid': False}, {'index': 9, 'value': 7, 'row': 1, 'column': 0, 'box': 0, 'potential': False, 'solid': True}, {'index': 10, 'value': 8, 'row': 1, 'column': 1, 'box': 0, 'potential': False, 'solid': True}, {'index': 11, 'value': 9, 'row': 1, 'column': 2, 'box': 0, 'potential': False, 'solid': False}, {'index': 
12, 'value': 3, 'row': 1, 'column': 3, 'box': 1, 'potential': False, 'solid': False}, {'index': 13, 'value': 2, 'row': 1, 'column': 4, 'box': 1, 'potential': False, 'solid': False}, {'index': 14, 'value': 1, 'row': 1, 'column': 5, 'box': 1, 'potential': False, 'solid': True}, {'index': 15, 'value': 5, 'row': 1, 'column': 6, 'box': 2, 'potential': False, 'solid': True}, {'index': 16, 'value': 6, 'row': 1, 'column': 7, 'box': 2, 'potential': False, 'solid': False}, {'index': 17, 'value': 4, 'row': 1, 'column': 8, 'box': 2, 'potential': False, 'solid': False}, {'index': 18, 'value': 4, 'row': 2, 'column': 0, 'box': 0, 'potential': False, 'solid': False}, {'index': 19, 'value': 3, 'row': 2, 'column': 1, 'box': 0, 'potential': False, 'solid': False}, {'index': 20, 'value': 6, 'row': 2, 'column': 2, 'box': 0, 'potential': False, 'solid': True}, {'index': 21, 'value': 9, 'row': 2, 'column': 3, 'box': 1, 'potential': False, 'solid': False}, {'index': 22, 'value': 8, 'row': 2, 'column': 4, 'box': 1, 'potential': False, 'solid': False}, {'index': 23, 'value': 5, 'row': 2, 'column': 5, 'box': 1, 'potential': False, 'solid': True}, {'index': 24, 'value': 2, 'row': 2, 'column': 6, 'box': 2, 'potential': [7], 'solid': False}, {'index': 25, 'value': 1, 'row': 2, 'column': 7, 'box': 2, 'potential': False, 'solid': True}, {'index': 26, 'value': 7, 'row': 2, 'column': 8, 'box': 2, 'potential': False, 'solid': False}, {'index': 27, 'value': 3, 'row': 3, 'column': 0, 'box': 3, 'potential': False, 'solid': True}, {'index': 28, 'value': 9, 'row': 3, 'column': 1, 'box': 3, 'potential': False, 'solid': True}, {'index': 29, 'value': 8, 'row': 3, 'column': 2, 'box': 3, 'potential': False, 'solid': True}, {'index': 30, 'value': 1, 'row': 3, 'column': 3, 'box': 4, 'potential': [7], 'solid': False}, {'index': 31, 'value': 6, 'row': 3, 'column': 4, 'box': 4, 'potential': False, 'solid': True}, {'index': 32, 'value': 2, 'row': 3, 'column': 5, 'box': 4, 'potential': False, 'solid': True}, {'index': 
33, 'value': 7, 'row': 3, 'column': 6, 'box': 5, 'potential': False, 'solid': False}, {'index': 34, 'value': 4, 'row': 3, 'column': 7, 'box': 5, 'potential': False, 'solid': False}, {'index': 35, 'value': 5, 'row': 3, 'column': 8, 'box': 5, 'potential': False, 'solid': False}, {'index': 36, 'value': 6, 'row': 4, 'column': 0, 'box': 3, 'potential': False, 'solid': False}, {'index': 37, 'value': 5, 'row': 4, 'column': 1, 'box': 3, 'potential': False, 'solid': True}, {'index': 38, 'value': 4, 'row': 4, 'column': 2, 'box': 3, 'potential': False, 'solid': True}, {'index': 39, 'value': 7, 'row': 4, 'column': 3, 'box': 4, 'potential': False, 'solid': False}, {'index': 40, 'value': 9, 'row': 4, 'column': 4, 'box': 4, 'potential': False, 'solid': False}, {'index': 41, 'value': 3, 'row': 4, 'column': 5, 'box': 4, 'potential': False, 'solid': True}, {'index': 42, 'value': 1, 'row': 4, 'column': 6, 'box': 5, 'potential': False, 'solid': False}, {'index': 43, 'value': 2, 'row': 4, 'column': 7, 'box': 5, 'potential': False, 'solid': True}, {'index': 44, 'value': 8, 'row': 4, 'column': 8, 'box': 5, 'potential': False, 'solid': True}, {'index': 45, 'value': 1, 'row': 5, 'column': 0, 'box': 3, 'potential': False, 'solid': True}, {'index': 46, 'value': 2, 'row': 5, 'column': 1, 'box': 3, 'potential': [7], 'solid': False}, {'index': 47, 'value': 7, 'row': 5, 'column': 2, 'box': 3, 'potential': False, 'solid': False}, {'index': 48, 'value': 4, 'row': 5, 'column': 3, 'box': 4, 'potential': False, 'solid': True}, {'index': 49, 'value': 5, 'row': 5, 'column': 4, 'box': 
4, 'potential': False, 'solid': False}, {'index': 50, 'value': 8, 'row': 5, 'column': 5, 'box': 4, 'potential': False, 'solid': True}, {'index': 51, 'value': 9, 'row': 5, 'column': 6, 'box': 5, 'potential': False, 'solid': True}, {'index': 52, 'value': 3, 'row': 5, 'column': 7, 'box': 
5, 'potential': False, 'solid': False}, {'index': 53, 'value': 6, 'row': 5, 'column': 8, 'box': 5, 'potential': False, 'solid': True}, {'index': 54, 'value': 5, 'row': 6, 'column': 0, 'box': 6, 'potential': False, 'solid': True}, {'index': 55, 'value': 7, 'row': 6, 'column': 1, 'box': 
6, 'potential': False, 'solid': False}, {'index': 56, 'value': 1, 'row': 6, 'column': 2, 'box': 6, 'potential': False, 'solid': False}, {'index': 57, 'value': 2, 'row': 6, 'column': 3, 'box': 7, 'potential': False, 'solid': True}, {'index': 58, 'value': 4, 'row': 6, 'column': 4, 'box': 7, 'potential': False, 'solid': False}, {'index': 59, 'value': 6, 'row': 6, 'column': 5, 'box': 7, 'potential': False, 'solid': True}, {'index': 60, 'value': 3, 'row': 6, 'column': 6, 'box': 8, 'potential': False, 'solid': True}, {'index': 61, 'value': 8, 'row': 6, 'column': 7, 'box': 8, 'potential': False, 'solid': True}, {'index': 62, 'value': 9, 'row': 6, 'column': 8, 'box': 8, 'potential': False, 'solid': True}, {'index': 63, 'value': 9, 'row': 7, 'column': 0, 'box': 6, 'potential': False, 'solid': True}, {'index': 64, 'value': 6, 'row': 7, 'column': 1, 'box': 
6, 'potential': False, 'solid': False}, {'index': 65, 'value': 2, 'row': 7, 'column': 2, 'box': 6, 'potential': False, 'solid': True}, {'index': 66, 'value': 8, 'row': 7, 'column': 3, 'box': 7, 'potential': False, 'solid': False}, {'index': 67, 'value': 3, 'row': 7, 'column': 4, 'box': 7, 'potential': False, 'solid': False}, {'index': 68, 'value': 7, 'row': 7, 'column': 5, 'box': 7, 'potential': False, 'solid': True}, {'index': 69, 'value': 4, 'row': 7, 'column': 6, 'box': 8, 'potential': False, 'solid': True}, {'index': 70, 'value': 5, 'row': 7, 'column': 7, 'box': 8, 'potential': False, 'solid': True}, {'index': 71, 'value': 1, 'row': 7, 'column': 8, 'box': 8, 'potential': False, 'solid': False}, {'index': 72, 'value': 8, 'row': 8, 'column': 0, 'box': 6, 'potential': False, 'solid': True}, {'index': 73, 'value': 4, 'row': 8, 'column': 1, 'box': 6, 'potential': False, 'solid': False}, {'index': 74, 'value': 3, 'row': 8, 'column': 2, 'box': 6, 'potential': False, 'solid': True}, {'index': 75, 'value': 5, 'row': 8, 'column': 3, 'box': 7, 'potential': False, 'solid': True}, {'index': 76, 'value': 1, 'row': 8, 'column': 4, 'box': 7, 'potential': False, 'solid': False}, {'index': 77, 'value': 9, 'row': 8, 'column': 5, 'box': 7, 'potential': False, 'solid': False}, {'index': 78, 'value': 6, 'row': 8, 'column': 6, 'box': 8, 'potential': False, 'solid': False}, {'index': 79, 'value': 7, 'row': 8, 'column': 7, 'box': 8, 'potential': False, 'solid': False}, {'index': 80, 'value': 2, 'row': 8, 'column': 8, 'box': 8, 'potential': False, 'solid': True}]

sudoku = [[0, 1, 0, 0, 0, 0, 8, 9, 0], [7, 8, 0, 0, 0, 1, 5, 0, 0], [0, 0, 6, 0, 0, 5, 0, 1, 0], [3, 9, 8, 0, 6, 2, 0, 0, 0], [0, 5, 4, 0, 0, 3, 0, 2, 8], [1, 0, 0, 4, 0, 8, 9, 0, 6], [5, 0, 0, 2, 0, 6, 3, 8, 9], [9, 0, 2, 0, 0, 7, 4, 5, 0], [8, 0, 3, 5, 0, 0, 0, 0, 2]]

def test_read():
    assert read("test1.csv") == sudoku

def test_get_dict():
    assert get_dict(sudoku) == dictitonary

def test_check_values():
    assert check_values(dictitonary) == result


